### ISSUE TITLE
Delay in theme load

### ISSUE THREAD

**Issue by narcolepticinsomniac** [mauricecruz/devtools-theme-loader#1]
Since you're fond of customizing CSS, I'm sure you're familiar with the Stylish extension. The Chrome version has made some recent improvements in terms of applying userstyles much more seamlessly. I'm guessing there's probably a decent chance that their method could be modified to apply themes to Devtools.

https://github.com/JasonBarnabe/stylish-chrome/blob/master/apply.js

**Comment by mauricecruz** [comment]
Thanks for the link. I have this extension but I never looked into the code.

For devtools, the injection of stylesheets is encapsulated in a method they wrote. 

``` javascript
_onApplyStyleSheet: function(message) 
    {
        if (!Runtime.experiments.isEnabled("applyCustomStylesheet"))
            return;
        var styleSheet = createElement("style");
        styleSheet.textContent = message.styleSheet;
        document.head.appendChild(styleSheet);
    }
```

Devtools is sandboxed so there's no other way to do it right now. But maybe I can offer a patch to them that will improve the load speed.
